name: Laravel Testing

on:
   pull_request:

jobs:
  laravel-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Event1
        run: echo "${{ github.event.action }}"

      - name: Event2
        run: echo "${{ github.event_name }}"

      - name: "Post Comment"
        uses: actions/github-script@v3
        env:
          MESSAGE: |
            デプロイを開始しました (名前:${{ steps.command.outputs.command-name }}, 引数:${{ steps.command.outputs.command-arguments }})
            ブランチ: ${{ steps.comment-branch.outputs.head_ref }}
            SHA: ${{ steps.comment-branch.outputs.head_sha }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })

#      - name: Docker Version
#        run: docker version
#
#      - name: Build Docker Images
#        run: docker-compose build
#
#      - name: Create & Start Docker Containers
#        run: docker-compose up -d
#
#      - name: OS Version
#        run: |
#          docker-compose exec -T app cat /etc/os-release
#          docker-compose exec -T app cat /etc/debian_version
#
#      - name: PHP Version
#        run: docker-compose exec -T app php --version
#
#      - name: Composer Version
#        run: docker-compose exec -T app composer --version
#
#      - name: Install Dependencies
#        run: docker-compose exec -T app composer install
#
#      - name: Laravel Version
#        run: docker-compose exec -T app php artisan --version
#
#      - name: Laravel Setting
#        run: |
#          docker-compose exec -T app cp .env.example .env
#          docker-compose exec -T app php artisan key:generate
#          docker-compose exec -T app php artisan config:clear
#
#      - name: Laravel Migrate Testing
#        run: docker-compose exec -T app php artisan migrate
#
#      - name: Laravel Rollback Testing
#        run: docker-compose exec -T app php artisan migrate:refresh
#
#      - name: Laravel Seeding Testing
#        run: docker-compose exec -T app php artisan db:seed
#
#      - name: Laravel PHPUnit Testing
#        run: docker-compose exec -T app php artisan test